---
plugins/chiliproject_activity_module:
  repository: "https://github.com/finnlabs/chiliproject_activity_module.git"
  branch: master
plugins/help_link:
  repository: "https://github.com/finnlabs/help_link.git"
  branch: master
plugins/numbered_headings:
  repository: "https://github.com/finnlabs/numbered_headings.git"
  branch: master
plugins/redmine_checkout:
  repository: "https://github.com/finnlabs/redmine_checkout.git"
  branch: master
plugins/customize_modules:
  repository: "https://github.com/finnlabs/customize_modules.git"
  branch: master
plugins/redmine_favicon:
  repository: "https://github.com/finnlabs/redmine_favicon.git"
  branch: master
plugins/memcached_passenger:
  repository: "https://github.com/finnlabs/memcached_passenger.git"
  branch: master

